spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/mp?&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
#    password: root
#    hikari:
#      minimum-idle: 5
#      idle-timeout: 600000
#      maximum-pool-size: 10
#      auto-commit: true
#      pool-name: MyHikariCP
#      max-lifetime: 1800000
#      connection-timeout: 30000
#      connection-test-query: SELECT 1
#logging:
#  level:
#    root: info
#    net.mujiwulian.mapper: debug
#    net.mujiwulian.configs: debug
#    net.mujiwulian.utils: debug
#    net.mujiwulian.aop: info
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**.xml
